// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package csr_pkg;

    localparam CSR_DATA_WIDTH = 32;
    localparam CSR_MIN_ADDR_WIDTH = 4;
    localparam CSR_SIZE = 'hc;

    typedef struct {
        logic value;
    } csr__DG_ENABLE__enable__out_t;

    typedef struct {
        csr__DG_ENABLE__enable__out_t enable;
    } csr__DG_ENABLE__out_t;

    typedef struct {
        logic [31:0] value;
    } csr__DG_LENGTH__length__out_t;

    typedef struct {
        csr__DG_LENGTH__length__out_t length;
    } csr__DG_LENGTH__out_t;

    typedef struct {
        logic value;
    } csr__SEL__sel__out_t;

    typedef struct {
        csr__SEL__sel__out_t sel;
    } csr__SEL__out_t;

    typedef struct {
        csr__DG_ENABLE__out_t DG_ENABLE;
        csr__DG_LENGTH__out_t DG_LENGTH;
        csr__SEL__out_t SEL;
    } csr__out_t;
endpackage
