# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jakub/proj-zybo/setup-z7-10/hw/vivado/counter/counter.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
# IP: The module: 'design_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jakub/proj-zybo/setup-z7-10/hw/vivado/counter/counter.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jakub/proj-zybo/setup-z7-10/hw/vivado/counter/counter.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
# IP: The module: 'design_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jakub/proj-zybo/setup-z7-10/hw/vivado/counter/counter.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
