// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package csr_pkg;

    localparam CSR_DATA_WIDTH = 32;
    localparam CSR_MIN_ADDR_WIDTH = 3;
    localparam CSR_SIZE = 'h4;

    typedef struct {
        logic [31:0] value;
    } csr__INCREMENT__increment__out_t;

    typedef struct {
        csr__INCREMENT__increment__out_t increment;
    } csr__INCREMENT__out_t;

    typedef struct {
        csr__INCREMENT__out_t INCREMENT;
    } csr__out_t;
endpackage
